name: Health check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-r0bert1.onrender.com/health